### ISSUE TITLE
Fix styling of pagination

### ISSUE THREAD

**Issue by bnijenhuis** [fronteers/website#373]
The pagination on for example https://fronteers.netlify.app/nl/werk-en-freelance/ is off and needs to be fixed. It's caused by the following CSS:

``` css
.pagination__page-number {
  margin: -.5em;
}
```

Removing the negative margin fixes it, but not sure where else it's used.
